version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # TODO no support for swift yet
  # - package-ecosystem: "swift"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
