name: Build & Release

on:
  push:
    branches:
      - main

# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

      - name: Build Release Binary
        run: swift build -v -c release --arch arm64 --arch x86_64

      - name: Zip Release Binary
        run: zip -r hyper-focus.zip .build/apple/Products/Release/hyper-focus

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hyper-focus.zip
          draft: true

