name: Build & Release

on:
  push:
    # branches: [main]
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    # TODO need ventura macos version https://github.com/actions/runner-images/issues/6426 to fix weird test issue
    #   https://github.com/actions/runner-images/issues/6642
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          # without check-mode, only the diff is checked, but there is no delta
          # when running within the context of a tag push
          check-mode: all

      - name: setup Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.2.app

      - name: Test
        run: swift test -vv

      - name: Build Release Binary
        run: swift build -v -c release --arch arm64 --arch x86_64

      - name: Zip Release Binary
        run: zip -rj hyper-focus.zip .build/apple/Products/Release/hyper-focus

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hyper-focus.zip
          generate_release_notes: true
